/* math_names.h - lib/libc/math.c's functions under other names, so that
 * the PC's build of it links beside the PC's own libm (test_math.py
 * passes -include math_names.h), and math99.c's and mathf.c's beside them.
 * Its sqrt is softfp.c's sf64_sqrt, its fma sf64_fma. */

#define acos am_acos
#define asin am_asin
#define atan am_atan
#define atan2 am_atan2
#define cos am_cos
#define sin am_sin
#define tan am_tan
#define cosh am_cosh
#define sinh am_sinh
#define tanh am_tanh
#define exp am_exp
#define frexp am_frexp
#define ldexp am_ldexp
#define log am_log
#define log10 am_log10
#define modf am_modf
#define pow am_pow
#define sqrt am_sqrt
#define ceil am_ceil
#define fabs am_fabs
#define floor am_floor
#define fmod am_fmod
#define __sf64_sqrt sf64_sqrt
/* C99's (math99.c, mathf.c), and the helpers they share with math.c */
#define acosh am_acosh
#define asinh am_asinh
#define atanh am_atanh
#define exp2 am_exp2
#define expm1 am_expm1
#define log1p am_log1p
#define log2 am_log2
#define logb am_logb
#define cbrt am_cbrt
#define erf am_erf
#define erfc am_erfc
#define lgamma am_lgamma
#define tgamma am_tgamma
#define nearbyint am_nearbyint
#define rint am_rint
#define round am_round
#define trunc am_trunc
#define hypot am_hypot
#define remainder am_remainder
#define copysign am_copysign
#define fdim am_fdim
#define fmax am_fmax
#define fmin am_fmin
#define nextafter am_nextafter
#define nexttoward am_nexttoward
#define scalbn am_scalbn
#define scalbln am_scalbln
#define ilogb am_ilogb
#define lrint am_lrint
#define llrint am_llrint
#define lround am_lround
#define llround am_llround
#define remquo am_remquo
#define nan am_nan
#define fma am_fma
#define acosf am_acosf
#define acosl am_acosl
#define asinf am_asinf
#define asinl am_asinl
#define atanf am_atanf
#define atanl am_atanl
#define cosf am_cosf
#define cosl am_cosl
#define sinf am_sinf
#define sinl am_sinl
#define tanf am_tanf
#define tanl am_tanl
#define acoshf am_acoshf
#define acoshl am_acoshl
#define asinhf am_asinhf
#define asinhl am_asinhl
#define atanhf am_atanhf
#define atanhl am_atanhl
#define coshf am_coshf
#define coshl am_coshl
#define sinhf am_sinhf
#define sinhl am_sinhl
#define tanhf am_tanhf
#define tanhl am_tanhl
#define expf am_expf
#define expl am_expl
#define exp2f am_exp2f
#define exp2l am_exp2l
#define expm1f am_expm1f
#define expm1l am_expm1l
#define logf am_logf
#define logl am_logl
#define log10f am_log10f
#define log10l am_log10l
#define log1pf am_log1pf
#define log1pl am_log1pl
#define log2f am_log2f
#define log2l am_log2l
#define logbf am_logbf
#define logbl am_logbl
#define cbrtf am_cbrtf
#define cbrtl am_cbrtl
#define fabsf am_fabsf
#define fabsl am_fabsl
#define sqrtf am_sqrtf
#define sqrtl am_sqrtl
#define erff am_erff
#define erfl am_erfl
#define erfcf am_erfcf
#define erfcl am_erfcl
#define lgammaf am_lgammaf
#define lgammal am_lgammal
#define tgammaf am_tgammaf
#define tgammal am_tgammal
#define ceilf am_ceilf
#define ceill am_ceill
#define floorf am_floorf
#define floorl am_floorl
#define nearbyintf am_nearbyintf
#define nearbyintl am_nearbyintl
#define rintf am_rintf
#define rintl am_rintl
#define roundf am_roundf
#define roundl am_roundl
#define truncf am_truncf
#define truncl am_truncl
#define atan2f am_atan2f
#define atan2l am_atan2l
#define hypotf am_hypotf
#define hypotl am_hypotl
#define powf am_powf
#define powl am_powl
#define fmodf am_fmodf
#define fmodl am_fmodl
#define remainderf am_remainderf
#define remainderl am_remainderl
#define copysignf am_copysignf
#define copysignl am_copysignl
#define fdimf am_fdimf
#define fdiml am_fdiml
#define fmaxf am_fmaxf
#define fmaxl am_fmaxl
#define fminf am_fminf
#define fminl am_fminl
#define nextafterf am_nextafterf
#define nextafterl am_nextafterl
#define nexttowardf am_nexttowardf
#define nexttowardl am_nexttowardl
#define frexpf am_frexpf
#define frexpl am_frexpl
#define ldexpf am_ldexpf
#define ldexpl am_ldexpl
#define modff am_modff
#define modfl am_modfl
#define scalbnf am_scalbnf
#define scalbnl am_scalbnl
#define scalblnf am_scalblnf
#define scalblnl am_scalblnl
#define ilogbf am_ilogbf
#define ilogbl am_ilogbl
#define lrintf am_lrintf
#define lrintl am_lrintl
#define llrintf am_llrintf
#define llrintl am_llrintl
#define lroundf am_lroundf
#define lroundl am_lroundl
#define llroundf am_llroundf
#define llroundl am_llroundl
#define remquof am_remquof
#define remquol am_remquol
#define nanf am_nanf
#define nanl am_nanl
#define fmaf am_fmaf
#define fmal am_fmal
#define __fpclassify am__fpclassify
#define __fpclassifyf am__fpclassifyf
#define __signbit am__signbit
#define __signbitf am__signbitf
#define __isgreater am__isgreater
#define __isgreaterequal am__isgreaterequal
#define __isless am__isless
#define __islessequal am__islessequal
#define __islessgreater am__islessgreater
#define __isunordered am__isunordered
#define __trunc am__trunc
#define __expm1 am__expm1
#define __sf64_fma sf64_fma
