"""Generate the 32-bit helper tests: one assembly program per helper in
lib/rt/rt.s's v1 set, each checking a table of operands against answers
computed here with C's semantics (abi.md sections 2 and 6).

    gen_ltests.py OUT_DIR       writes OUT_DIR/l_<helper>.asm

Each program exits (port 0) with 0 if every row passes, else the number of
the first failing row (1-based, at most 200 rows per program). Rows set the
registers the helper's contract names - left in A:UBC, right in E:UHL; a
shift's count in HL; a unary helper's operand in E:UHL; __itol's int in
HL - poison the unspecified D, then compare E:UHL (HL only where the
result is an int). Compares also check Z against the result, and every
row checks IX and SP survive.
"""
import os, random, sys

M32 = 0xFFFFFFFF


def s32(v):
    v &= M32
    return v - (1 << 32) if v & 0x80000000 else v


def trunc_div(a, b):
    q = abs(a) // abs(b)
    return q if (a < 0) == (b < 0) else -q


EDGES = [0, 1, 2, 3, 7, 0xFF, 0x100, 0xFFFF, 0x10000, 0x7FFFFF, 0x800000, 0xFFFFFF, 0x1000000,
         0x12345678, 0x7FFFFFFF, 0x80000000, 0x80000001, 0xFFFFFFFE, 0xFFFFFFFF, 0xFF000000,
         0x00FF00FF, 0xDEADBEEF, 100000, 1000000007 & M32]


def operands(rng, count, nonzero_right=False, avoid_min_neg1=False):
    pairs = []
    for a in EDGES[:12]:
        for b in (EDGES[1], EDGES[5], EDGES[13], EDGES[15], EDGES[18]):
            pairs.append((a, b))
    for a in EDGES:
        pairs.append((a, a))
    while len(pairs) < count:
        kind = rng.randrange(4)
        if kind == 0:
            pairs.append((rng.getrandbits(32), rng.getrandbits(32)))
        elif kind == 1:
            pairs.append((rng.getrandbits(32), rng.getrandbits(rng.randrange(1, 17))))
        elif kind == 2:
            pairs.append((rng.choice(EDGES), rng.getrandbits(32)))
        else:
            pairs.append((rng.getrandbits(rng.randrange(1, 33)), rng.choice(EDGES)))
    out = []
    for a, b in pairs:
        if nonzero_right and b == 0:
            b = 1
        if avoid_min_neg1 and a == 0x80000000 and b == M32:
            b = 3
        out.append((a & M32, b & M32))
    return out[:count]


# helper -> (kind, function of (a, b) giving the expected 32-bit result or 0/1)
BINARY = {
    "__ladd": lambda a, b: (a + b) & M32,
    "__lsub": lambda a, b: (a - b) & M32,
    "__lmul": lambda a, b: (a * b) & M32,
    "__land": lambda a, b: a & b,
    "__lor": lambda a, b: a | b,
    "__lxor": lambda a, b: a ^ b,
    "__ldivu": lambda a, b: a // b,
    "__lremu": lambda a, b: a % b,
    "__ldivs": lambda a, b: trunc_div(s32(a), s32(b)) & M32,
    "__lrems": lambda a, b: (s32(a) - trunc_div(s32(a), s32(b)) * s32(b)) & M32,
}
COMPARE = {
    "__lltu": lambda a, b: int(a < b),
    "__lleu": lambda a, b: int(a <= b),
    "__llts": lambda a, b: int(s32(a) < s32(b)),
    "__lles": lambda a, b: int(s32(a) <= s32(b)),
    "__leq": lambda a, b: int(a == b),
}
SHIFT = {
    "__lshl": lambda a, n: (a << n) & M32,
    "__lshru": lambda a, n: a >> n,
    "__lshrs": lambda a, n: (s32(a) >> n) & M32,
}
UNARY = {
    "__lneg": lambda b: (-b) & M32,
    "__lcpl": lambda b: ~b & M32,
}

HEADER = """; Generated by tests/rt/gen_ltests.py: {name}. Exits with 0, or the
; number of the first failing row.
        assume  adl=1
        org     0x040000

        jp      start
        align   64
        db      "MOS", 0, 1

__bss_base:      equ     0x0AFF00
__idivu_buf:     equ     __bss_base+0
__iremu_buf:     equ     __bss_base+6
__idivs_neg:     equ     __bss_base+12
__irems_neg:     equ     __bss_base+13
__ishru_buf:     equ     __bss_base+14
__ishrs_buf:     equ     __bss_base+17
__sext8_buf:     equ     __bss_base+20
__sext16_buf:    equ     __bss_base+23
__imul_buf:      equ     __bss_base+26
__imul_res:      equ     __bss_base+32

        include "lib\\rt\\rt.s"

start:
        ld      ix, 0x0A5A5A            ; must survive every call
        ld      (saved_sp), sp
"""

FOOTER = """        xor     a
        out0    (0x00), a
@spin:  jr      @spin

; A failing row: exit with its number, in A.
fail:
        out0    (0x00), a
@spin2: jr      @spin2

; After each call: IX unchanged, else fail with the row (in A). Keeps HL
; and AF; clobbers BC.
check_frame:
        push    af
        push    hl
        push    ix
        pop     hl
        ld      bc, 0x0A5A5A
        or      a
        sbc     hl, bc
        pop     hl
        jr      nz, @bad
        pop     af
        ret
@bad:
        pop     af
        jr      fail

saved_sp:       dl      0
after_sp:       dl      0
zflag:          db      0
"""


def row_code(i, setup, call, expect_hl, expect_e, compare):
    lines = [f"; row {i}"] + setup + [
        "        ld      d, 0xA5                 ; D is unspecified: poison it",
        f"        call    {call}",
    ]
    if compare:
        # Z must be set iff the result is 0: record it before anything else
        lines += ["        push    af", "        pop     bc", "        ld      a, c",
                  "        and     0x40", "        ld      (zflag), a"]
    lines += ["        ld      (after_sp), sp", f"        ld      a, {i}", "        call    check_frame",
              f"        ld      bc, 0x{expect_hl:06X}", "        or      a", "        sbc     hl, bc",
              f"        ld      a, {i}", "        jp      nz, fail"]
    if expect_e is not None:
        lines += ["        ld      a, e", f"        cp      0x{expect_e:02X}", f"        ld      a, {i}",
                  "        jp      nz, fail"]
    if compare:
        lines += ["        ld      a, (zflag)", f"        cp      0x{0x40 if expect_hl == 0 else 0:02X}",
                  f"        ld      a, {i}", "        jp      nz, fail"]
    lines += ["        ld      hl, (after_sp)", "        ld      bc, (saved_sp)", "        or      a",
              "        sbc     hl, bc", f"        ld      a, {i}", "        jp      nz, fail"]
    return lines


def setup_binary(a, b):
    return [f"        ld      bc, 0x{a & 0xFFFFFF:06X}", f"        ld      hl, 0x{b & 0xFFFFFF:06X}",
            f"        ld      e, 0x{b >> 24:02X}", f"        ld      a, 0x{a >> 24:02X}"]


def generate(out_dir, seed=1989, wrong=None):
    """wrong = (helper, row): that row expects its answer plus one (the guard)."""
    rng = random.Random(seed)
    os.makedirs(out_dir, exist_ok=True)
    programs = {}
    for name, fn in BINARY.items():
        divide = "div" in name or "rem" in name
        rows = []
        for i, (a, b) in enumerate(operands(rng, 200, nonzero_right=divide,
                                            avoid_min_neg1=name in ("__ldivs", "__lrems")), 1):
            r = fn(a, b)
            if wrong == (name, i):
                r = (r + 1) & M32
            rows += row_code(i, setup_binary(a, b), name, r & 0xFFFFFF, r >> 24, False)
        programs[name] = rows
    for name, fn in COMPARE.items():
        rows = []
        for i, (a, b) in enumerate(operands(rng, 200), 1):
            rows += row_code(i, setup_binary(a, b), name, fn(a, b), None, True)
        programs[name] = rows
    for name, fn in SHIFT.items():
        rows = []
        for i in range(1, 201):
            a = rng.choice(EDGES) if i % 3 == 0 else rng.getrandbits(32)
            n = (i - 1) % 32
            r = fn(a, n)
            setup = [f"        ld      bc, 0x{a & 0xFFFFFF:06X}", f"        ld      hl, {n}",
                     "        ld      e, 0x5A", f"        ld      a, 0x{a >> 24:02X}"]
            rows += row_code(i, setup, name, r & 0xFFFFFF, r >> 24, False)
        programs[name] = rows
    for name, fn in UNARY.items():
        rows = []
        for i, (a, b) in enumerate(operands(rng, 200), 1):
            r = fn(b)
            setup = ["        ld      bc, 0x5A5A5A", f"        ld      hl, 0x{b & 0xFFFFFF:06X}",
                     f"        ld      e, 0x{b >> 24:02X}", "        ld      a, 0x5A"]
            rows += row_code(i, setup, name, r & 0xFFFFFF, r >> 24, False)
        programs[name] = rows
    rows = []                                   # __lnz: E:UHL != 0, as a compare
    for i, (a, b) in enumerate(operands(rng, 200), 1):
        if i % 4 == 0:
            b = 0
        setup = ["        ld      bc, 0x5A5A5A", f"        ld      hl, 0x{b & 0xFFFFFF:06X}",
                 f"        ld      e, 0x{b >> 24:02X}", "        ld      a, 0x5A"]
        rows += row_code(i, setup, "__lnz", int(b != 0), None, True)
    programs["__lnz"] = rows
    rows = []                                   # __itol: HL (a canonical int) -> E:UHL
    for i in range(1, 201):
        v = rng.choice([0, 1, 0x7FFFFF, 0x800000, 0xFFFFFF, 0x123456, 0xFEDCBA]) if i <= 40 else rng.getrandbits(24)
        r = (v - (1 << 24) if v & 0x800000 else v) & M32
        setup = ["        ld      bc, 0x5A5A5A", f"        ld      hl, 0x{v:06X}", "        ld      e, 0x5A",
                 "        ld      a, 0x5A"]
        rows += row_code(i, setup, "__itol", r & 0xFFFFFF, r >> 24, False)
    programs["__itol"] = rows
    rows = []                                   # __utol: HL -> E:UHL, zero-extended
    for i in range(1, 51):
        v = rng.getrandbits(24)
        setup = ["        ld      bc, 0x5A5A5A", f"        ld      hl, 0x{v:06X}", "        ld      e, 0x5A",
                 "        ld      a, 0x5A"]
        rows += row_code(i, setup, "__utol", v, 0, False)
    programs["__utol"] = rows
    rows = []                                   # __ltoi: E:UHL -> HL, the low 24 bits
    for i in range(1, 51):
        v = rng.getrandbits(32)
        setup = ["        ld      bc, 0x5A5A5A", f"        ld      hl, 0x{v & 0xFFFFFF:06X}",
                 f"        ld      e, 0x{v >> 24:02X}", "        ld      a, 0x5A"]
        rows += row_code(i, setup, "__ltoi", v & 0xFFFFFF, None, False)
    programs["__ltoi"] = rows
    names = []
    if wrong:
        programs = {wrong[0]: programs[wrong[0]]}
    for name, rows in programs.items():
        stem = "t_" + name[2:]
        with open(os.path.join(out_dir, stem + ".asm"), "w", newline="\n") as f:
            f.write(HEADER.format(name=name))
            f.write("\n".join(rows) + "\n")
            f.write(FOOTER)
        names.append(stem)
    return names


if __name__ == "__main__":
    for n in generate(sys.argv[1] if len(sys.argv) > 1 else os.path.join("build", "test", "rt", "long")):
        print(n)
