"""Tests for the hand-written runtime, lib/rt/crt0.s and lib/rt/rt.s.

    test_rt.py

Each test is an assembly program that includes the file under test,
assembled by the host's ez80asm and run on the emulator; pass/fail is its
port-0 exit code only, never printed text (the emulator's transcript is
not reliable enough).

crt0  startup and exit: argv splitting (none, whitespace, the 32-entry cap),
      bss zeroing (608 bytes, 64K and 64K + 1), the stack, IY, exit from
      deep in a call chain, and MOS stopping a script on a non-zero status
      (quit.bin, which would exit 0, must then never run: the harness
      reports 125).
rt    18 programs covering the 19 helpers (tests/rt/helpers/t_*.asm): each
      exits 0 when all its internal cases pass, else how many failed.
rt32  24 programs for the 32-bit helpers (v1), generated by gen_ltests.py
      into build/test/rt/long with answers computed in Python: 50-200 rows
      each of edge cases and random operands, checking the result, Z for
      compares, and that IX and SP survive; each exits 0 or the number of
      its first failing row. Guard: __ladd with row 7's answer made wrong
      must exit 7.
"""
import glob, os, shutil, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(REPO, "tests", "tools"))
from common import PY, EZ80ASM, RUN_EMULATOR  # noqa: E402
sys.path.insert(0, HERE)
import gen_ltests  # noqa: E402

CRT0 = os.path.join("tests", "rt", "crt0")
HELPERS = os.path.join("tests", "rt", "helpers")
LONG = os.path.join("build", "test", "rt", "long")
GUARD = os.path.join("build", "test", "rt", "guard")

# (case, the binaries it needs, autoexec lines, the exit code wanted)
CRT0_CASES = [
    ("t_ret0: HL=0 lets autoexec continue", ["t_ret0", "quit"], ["t_ret0", "quit"], 0),
    ("t_ret21: HL=21 stops autoexec, so quit never runs", ["t_ret21", "quit"], ["t_ret21", "quit"], 125),
    ("t_argv0: no arguments, argc 1, argv[0] empty", ["t_argv0"], ["t_argv0"], 0),
    ("t_argv1: arguments split, runs of spaces collapsed", ["t_argv1"], ["t_argv1 a bb  ccc"], 0),
    ("t_argv32: at most 32 entries", ["t_argv32"], ["t_argv32 " + " ".join(str(i) for i in range(1, 41))], 0),
    ("t_dirty then t_bss: bss really zeroed", ["t_dirty", "t_bss"], ["t_dirty", "t_bss"], 0),
    ("t_dirty64 then t_bss64: a 64K bss zeroed", ["t_dirty64", "t_bss64"], ["t_dirty64", "t_bss64"], 0),
    ("t_dirty64 then t_bss64p: a 64K + 1 bss zeroed", ["t_dirty64", "t_bss64p"], ["t_dirty64", "t_bss64p"], 0),
    ("t_stack: SP on entry to main", ["t_stack"], ["t_stack"], 0),
    ("t_exit: jp __exit from a deep call chain, HL=0", ["t_exit", "quit"], ["t_exit", "quit"], 0),
    ("t_exit21: jp __exit deep with HL=21 stops autoexec", ["t_exit21", "quit"], ["t_exit21", "quit"], 125),
    ("t_iy: IY clobbered by the program, still returns cleanly", ["t_iy", "quit"], ["t_iy", "quit"], 0),
]


def assemble(folder):
    """Every .asm in folder -> .bin beside it; returns the problems."""
    problems = []
    for src in sorted(glob.glob(os.path.join(REPO, folder, "*.asm"))):
        rel = os.path.relpath(src, REPO)
        r = subprocess.run([EZ80ASM, rel, rel[:-4] + ".bin"], cwd=REPO, capture_output=True, text=True)
        if r.returncode:
            problems.append(f"{rel}: {(r.stdout + r.stderr).strip()[:300]}")
    return problems


def emulate(folder, bins, cmds):
    args = [PY, RUN_EMULATOR]
    for b in bins:
        args += ["--bin", os.path.join(folder, b + ".bin")]
    for c in cmds:
        args += ["--cmd", c]
    return subprocess.run(args + ["--sdcard-name", "rt", "--timeout", "30"], cwd=REPO,
                          capture_output=True, text=True).returncode


def main():
    failed = 0
    problems = assemble(CRT0) + assemble(HELPERS)
    if problems:
        for p in problems:
            print("FAIL  assembling " + p)
        return 1
    for name, bins, cmds, want in CRT0_CASES:
        rc = emulate(CRT0, bins, cmds)
        print(("PASS  " if rc == want else "FAIL  ") + "crt0 " + name + ("" if rc == want else f" (got {rc}, wanted {want})"))
        failed += rc != want
    for src in sorted(glob.glob(os.path.join(REPO, HELPERS, "t_*.asm"))):
        stem = os.path.basename(src)[:-4]
        rc = emulate(HELPERS, [stem], [stem])
        print(("PASS  " if rc == 0 else "FAIL  ") + "rt " + stem + ("" if rc == 0 else f" ({rc} cases failed, or harness code {rc})"))
        failed += rc != 0
    for folder in (LONG, GUARD):
        if os.path.isdir(os.path.join(REPO, folder)):
            shutil.rmtree(os.path.join(REPO, folder))
    gen_ltests.generate(os.path.join(REPO, LONG))
    gen_ltests.generate(os.path.join(REPO, GUARD), wrong=("__ladd", 7))
    problems = assemble(LONG) + assemble(GUARD)
    for p in problems:
        print("FAIL  assembling " + p)
    failed += len(problems)
    if not problems:
        for src in sorted(glob.glob(os.path.join(REPO, LONG, "t_*.asm"))):
            stem = os.path.basename(src)[:-4]
            rc = emulate(LONG, [stem], [stem])
            print(("PASS  " if rc == 0 else "FAIL  ") + "rt32 " + stem + ("" if rc == 0 else f" (row {rc} failed, or harness code {rc})"))
            failed += rc != 0
        rc = emulate(GUARD, ["t_ladd"], ["t_ladd"])
        print(("PASS  " if rc == 7 else "FAIL  ") + f"rt32 guard: a wrong answer in row 7 is reported as 7 (got {rc})")
        failed += rc != 7
    print(f"{failed} failed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
