"""Tests for the hand-written runtime, lib/rt/crt0.s and lib/rt/rt.s.

    test_rt.py

Each test is an assembly program that includes the file under test,
assembled by the host's ez80asm and run on the emulator; pass/fail is its
port-0 exit code only, never printed text (the emulator's transcript is
not reliable enough).

crt0  startup and exit: argv splitting (none, whitespace, the 32-entry cap),
      bss zeroing (608 bytes, 64K and 64K + 1), the stack, IY, exit from
      deep in a call chain, and MOS stopping a script on a non-zero status
      (quit.bin, which would exit 0, must then never run: the harness
      reports 125).
rt    18 programs covering the 19 helpers (tests/rt/helpers/t_*.asm): each
      exits 0 when all its internal cases pass, else how many failed.
rt32  24 programs for the 32-bit helpers (v1), generated by gen_ltests.py
      into build/test/rt/long with answers computed in Python: 50-200 rows
      each of edge cases and random operands, checking the result, Z for
      compares, and that IX and SP survive; each exits 0 or the number of
      its first failing row. Guard: __ladd with row 7's answer made wrong
      must exit 7.
ref   the multiply and divide helpers against their C reference,
      lib/rt/rt_ref.c: rtref_gen.c, built and run on the PC, checks the
      reference against the PC's own arithmetic and writes 3,844 cases
      with its answers (every pair of edge values that reach each path of
      the helpers, and random ones); t_rtref.c runs C's * / % on them on
      the emulator, through __imul ... __lrems, and exits 0 or its first
      wrong row. Guard: row 7's product made wrong must exit 7. Needs
      make cross (it links libc.s for agon_emu_exit).
"""
import glob, os, re, shutil, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(REPO, "tests", "tools"))
from common import PY, EZ80ASM, RUN_EMULATOR, HOSTCC  # noqa: E402
sys.path.insert(0, HERE)
import gen_ltests  # noqa: E402

CRT0 = os.path.join("tests", "rt", "crt0")
HELPERS = os.path.join("tests", "rt", "helpers")
LONG = os.path.join("build", "test", "rt", "long")
GUARD = os.path.join("build", "test", "rt", "guard")
REF = os.path.join("build", "test", "rt", "ref")
HOST = os.path.join("build", "host")
LIBC = os.path.join("build", "agon", "lib", "agonc", "libc.s")

# (case, the binaries it needs, autoexec lines, the exit code wanted)
CRT0_CASES = [
    ("t_ret0: HL=0 lets autoexec continue", ["t_ret0", "quit"], ["t_ret0", "quit"], 0),
    ("t_ret21: HL=21 stops autoexec, so quit never runs", ["t_ret21", "quit"], ["t_ret21", "quit"], 125),
    ("t_argv0: no arguments, argc 1, argv[0] empty", ["t_argv0"], ["t_argv0"], 0),
    ("t_argv1: arguments split, runs of spaces collapsed", ["t_argv1"], ["t_argv1 a bb  ccc"], 0),
    ("t_argv32: at most 32 entries", ["t_argv32"], ["t_argv32 " + " ".join(str(i) for i in range(1, 41))], 0),
    ("t_dirty then t_bss: bss really zeroed", ["t_dirty", "t_bss"], ["t_dirty", "t_bss"], 0),
    ("t_dirty64 then t_bss64: a 64K bss zeroed", ["t_dirty64", "t_bss64"], ["t_dirty64", "t_bss64"], 0),
    ("t_dirty64 then t_bss64p: a 64K + 1 bss zeroed", ["t_dirty64", "t_bss64p"], ["t_dirty64", "t_bss64p"], 0),
    ("t_stack: SP on entry to main", ["t_stack"], ["t_stack"], 0),
    ("t_exit: jp __exit from a deep call chain, HL=0", ["t_exit", "quit"], ["t_exit", "quit"], 0),
    ("t_exit21: jp __exit deep with HL=21 stops autoexec", ["t_exit21", "quit"], ["t_exit21", "quit"], 125),
    ("t_iy: IY clobbered by the program, still returns cleanly", ["t_iy", "quit"], ["t_iy", "quit"], 0),
]


def assemble(folder):
    """Every .asm in folder -> .bin beside it; returns the problems."""
    problems = []
    for src in sorted(glob.glob(os.path.join(REPO, folder, "*.asm"))):
        rel = os.path.relpath(src, REPO)
        r = subprocess.run([EZ80ASM, rel, rel[:-4] + ".bin"], cwd=REPO, capture_output=True, text=True)
        if r.returncode:
            problems.append(f"{rel}: {(r.stdout + r.stderr).strip()[:300]}")
    return problems


def emulate(folder, bins, cmds):
    args = [PY, RUN_EMULATOR]
    for b in bins:
        args += ["--bin", os.path.join(folder, b + ".bin")]
    for c in cmds:
        args += ["--cmd", c]
    return subprocess.run(args + ["--sdcard-name", "rt", "--timeout", "30"], cwd=REPO,
                          capture_output=True, text=True).returncode


def ref_build(folder, wrong):
    """The cases (row `wrong`'s product made wrong, unless 0) and t_rtref.bin
    in folder; returns a problem string or None."""
    out = os.path.join(REPO, folder)
    os.makedirs(out, exist_ok=True)
    gen = os.path.join(out, "rtref_gen.exe")
    steps = [[HOSTCC, "-std=c99", "-O2", "-Wall", "-o", gen, os.path.join(HERE, "rtref_gen.c")],
             [gen, os.path.join(out, "rtref_cases.h")] + ([str(wrong)] if wrong else [])]
    o = lambda ext: os.path.join(folder, "t_rtref" + ext)
    steps += [[os.path.join(HOST, "cpp.exe"), os.path.join("tests", "rt", "t_rtref.c"), o(".i"),
               "-I", folder, "-I", os.path.join("lib", "libc"), "-I", "lib"],
              [os.path.join(HOST, "cc1.exe"), o(".i"), o(".ir"), "-u", "t_rtref.c"],
              [os.path.join(HOST, "cc2.exe"), o(".ir"), o(".s")] + ([] if os.environ.get("AGONC_TEST_O0") else ["-O"]),
              [os.path.join(HOST, "ld.exe"), "-o", o(".asm"), os.path.join("lib", "rt", "crt0.s"),
               os.path.join("lib", "rt", "rt.s"), LIBC, o(".s")],
              [EZ80ASM, o(".asm"), o(".bin")]]
    for cmd in steps:
        r = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True)
        if r.returncode:
            return f"{os.path.basename(cmd[0])}: {(r.stdout + r.stderr).strip()[:300]}"
    return None


def ref():
    """The ref section's two runs; returns the number failed."""
    failed = 0
    for name, folder, wrong, want in (("ref t_rtref: the helpers agree with rt_ref.c on every row", REF, 0, 0),
                                      ("ref guard: a wrong product in row 7 is reported as 7", REF + "_guard", 7, 7)):
        p = ref_build(folder, wrong)
        rc = p or subprocess.run([PY, RUN_EMULATOR, "--bin", os.path.join(folder, "t_rtref.bin"), "--cmd", "t_rtref",
                                  "--sdcard-name", "rt", "--timeout", "120"], cwd=REPO,
                                 capture_output=True, text=True).returncode
        print(("PASS  " if rc == want else "FAIL  ") + name + ("" if rc == want else f" (got {rc})"))
        failed += rc != want
    return failed


def main():
    failed = 0
    problems = assemble(CRT0) + assemble(HELPERS)
    if problems:
        for p in problems:
            print("FAIL  assembling " + p)
        return 1
    # argv[argc] must be null even with all 32 entries used: crt0's table
    # has 33 slots. The crt0 tests give their own bss size, and what follows
    # the table in a linked program may happen to be zero, so the
    # declaration itself is what is checked.
    m = re.search(r"^;;sect bss __argv g (\d+)$", open(os.path.join(REPO, "lib", "rt", "crt0.s")).read(), re.M)
    ok = m is not None and int(m.group(1)) == 3 * (32 + 1)
    print(("PASS  " if ok else "FAIL  ") + "crt0 __argv has 33 slots (99 bytes), so argv[argc] is null when 32 are used"
          + ("" if ok else f" (declared {m.group(1) if m else 'nowhere'})"))
    failed += not ok
    for name, bins, cmds, want in CRT0_CASES:
        rc = emulate(CRT0, bins, cmds)
        print(("PASS  " if rc == want else "FAIL  ") + "crt0 " + name + ("" if rc == want else f" (got {rc}, wanted {want})"))
        failed += rc != want
    for src in sorted(glob.glob(os.path.join(REPO, HELPERS, "t_*.asm"))):
        stem = os.path.basename(src)[:-4]
        rc = emulate(HELPERS, [stem], [stem])
        print(("PASS  " if rc == 0 else "FAIL  ") + "rt " + stem + ("" if rc == 0 else f" ({rc} cases failed, or harness code {rc})"))
        failed += rc != 0
    for folder in (LONG, GUARD):
        if os.path.isdir(os.path.join(REPO, folder)):
            shutil.rmtree(os.path.join(REPO, folder))
    gen_ltests.generate(os.path.join(REPO, LONG))
    gen_ltests.generate(os.path.join(REPO, GUARD), wrong=("__ladd", 7))
    problems = assemble(LONG) + assemble(GUARD)
    for p in problems:
        print("FAIL  assembling " + p)
    failed += len(problems)
    if not problems:
        for src in sorted(glob.glob(os.path.join(REPO, LONG, "t_*.asm"))):
            stem = os.path.basename(src)[:-4]
            rc = emulate(LONG, [stem], [stem])
            print(("PASS  " if rc == 0 else "FAIL  ") + "rt32 " + stem + ("" if rc == 0 else f" (row {rc} failed, or harness code {rc})"))
            failed += rc != 0
        rc = emulate(GUARD, ["t_ladd"], ["t_ladd"])
        print(("PASS  " if rc == 7 else "FAIL  ") + f"rt32 guard: a wrong answer in row 7 is reported as 7 (got {rc})")
        failed += rc != 7
    if os.path.exists(os.path.join(REPO, LIBC)):
        failed += ref()
    else:
        print("FAIL  ref: " + LIBC + " is missing (make cross)")
        failed += 1
    print(f"{failed} failed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
